// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///  df
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGaimfQKV0N56qhoDNTxEE9JNgUhysXo',
    appId: '1:223695938906:web:94f3a7e1c42ae8f7e7ff63',
    messagingSenderId: '223695938906',
    projectId: 'taskforce-hrms',
    authDomain: 'taskforce-hrms.firebaseapp.com',
    storageBucket: 'taskforce-hrms.appspot.com',
    measurementId: 'G-FG9J0TDF3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgRza5M_mKpA19YXZ2JoXzBRL4N_oaJk',
    appId: '1:223695938906:android:ec08fb9172414a04e7ff63',
    messagingSenderId: '223695938906',
    projectId: 'taskforce-hrms',
    storageBucket: 'taskforce-hrms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqg9I-jBNIuP9lbU_hTdTDbNUVidwPzc',
    appId: '1:223695938906:ios:6015134db70cd670e7ff63',
    messagingSenderId: '223695938906',
    projectId: 'taskforce-hrms',
    storageBucket: 'taskforce-hrms.appspot.com',
    iosClientId:
        '223695938906-90t0mp7mn1pd622ciiabpaodoi9fihf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskforcehrms.taskforceHrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqg9I-jBNIuP9lbU_hTdTDbNUVidwPzc',
    appId: '1:223695938906:ios:b189312fecf2efc6e7ff63',
    messagingSenderId: '223695938906',
    projectId: 'taskforce-hrms',
    storageBucket: 'taskforce-hrms.appspot.com',
    iosClientId:
        '223695938906-klim4irp5ea870tuvlm36of3nqnil2a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskforcehrms.taskforceHrms.RunnerTests',
  );
}
